import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  CASUALTY_FORMULA_TEMPLATES,
  createCasualtyMetricInstances,
  type DiagnosticMeasureExpression,
  type DiagnosticRoleExpression,
} from "@actuarial-ts/core";

const counts={reported:"reported",open:"open",closedNoPay:"closed-no-pay",closedWithPay:"closed-with-pay"};
const instances=createCasualtyMetricInstances({counts,exposure:"exposure",amountBindings:[{id:"basis",paid:"paid",incurred:"incurred"}]});
const expression=(value:DiagnosticMeasureExpression|DiagnosticRoleExpression):string=>{
  if(value.op==="measure")return value.measureId;
  if(value.op==="role")return value.role;
  if(value.op==="claim-layer")return `layer(${value.measureId}, ${value.attachment}, ${value.limit??"unlimited"})`;
  if(value.op==="subtract")return `(${expression(value.left)} - ${expression(value.right)})`;
  return `(${value.terms.map(expression).join(" + ")})`;
};
const lines=[
  "# Generalized diagnostic formula catalog",
  "",
  "> Generated by `npm run docs:diagnostics`; do not edit by hand.",
  "",
  "A formula is basis-independent arithmetic over typed roles. An instance binds those roles to caller-declared measures and adds presentation and review rules. Capping, gross/net treatment, expenses, exposure basis, and count population belong to measures/bases and bindings—not to duplicate formulas.",
  "",
  "Every division is ratio-of-sums at the selected cell grain. A missing numerator or denominator, or a non-positive denominator, produces `null`; the SDK never emits `NaN` or silently averages row ratios.",
  "",
  "## Formula templates",
  "",
  "| Order | ID | Roles | Numerator | Denominator | Policy |",
  "|---:|---|---|---|---|---|",
  ...CASUALTY_FORMULA_TEMPLATES.map((formula,index)=>`| ${index+1} | \`${formula.id}\` | ${Object.entries(formula.roles).map(([name,role])=>`\`${name}: ${role.kind}${role.compatibilityGroup?`/${role.compatibilityGroup}`:""}${role.developmentSemantics?`/${role.developmentSemantics}`:""}\``).join("<br>")} | \`${expression(formula.numerator)}\` | \`${expression(formula.denominator)}\` | \`${formula.denominatorPolicy}\` |`),
  "",
  "## Casualty factory output",
  "",
  "The sample below has ten count instances plus six instances for each caller amount basis: `10 + 6 × basisCount`. One basis therefore produces 16 instances; two produce 22. IDs and order are deterministic.",
  "",
  "| Order | Instance ID | Formula | Bindings | Scale / unit |",
  "|---:|---|---|---|---|",
  ...instances.map((instance,index)=>`| ${index+1} | \`${instance.id}\` | \`${instance.formulaId}\` | ${Object.entries(instance.bindings).map(([role,value])=>`\`${role}=${expression(value)}\``).join("<br>")} | ${instance.presentation.scale} / ${instance.presentation.displayUnit} |`),
  "",
  "## Generated instance rules",
  "",
  ...instances.flatMap((instance)=>instance.rules.map((rule)=>`- \`${rule.id}\` on \`${instance.id}\`: ${rule.message}; severity \`${rule.severity}\`, comparison \`${rule.when.left.source} ${rule.when.operator} ${rule.when.right.source}\`, absolute tolerance ${rule.when.tolerance?.absolute??0}, relative tolerance ${rule.when.tolerance?.relative??0}.`)),
  "",
  "## Caller-owned capped basis example",
  "",
  "Define measures such as `paid-primary-250k` and `incurred-primary-250k` with an `AmountBasisDefinition` whose component limitation records the attachment, limit, application level, and derivation. Bind those measures to the ordinary `paid-to-incurred`, `amount-per-exposure`, `amount-per-claim`, and `case-per-open` templates. The same formulas then serve unlimited, capped, gross, net, or ceded bases while calculation fingerprints remain distinct.",
  "",
  "## Identity scopes",
  "",
  "- Formula identity covers only the reusable role/arithmetic contract.",
  "- Calculation identity adds bindings, dependent measure semantics, populations/bases, derivations, and row grain.",
  "- Definition identity adds presentation, instance rules, review rules, period axis, and the full catalog.",
  "- Rule-only dependencies appear in semantic evaluation references without changing numeric calculation identity.",
  "",
].join("\n");
const target=resolve("docs/reference/diagnostic-formulas.md");
if(process.argv.includes("--check")){if(readFileSync(target,"utf8")!==lines)throw new Error(`${target} is stale; run npm run docs:diagnostics`)}else{mkdirSync(resolve("docs/reference"),{recursive:true});writeFileSync(target,lines)}
